// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"

	"github.com/google/uuid"
	"github.com/jilio/gqlgen-scalars/scalar"
)

type Asset interface {
	IsAsset()
	GetID() uuid.UUID
	GetSymbol() string
	GetName() string
	GetCurrency() string
	GetAssetClass() AssetClass
	GetLivePrice() scalar.Decimal
}

type EtfAsset struct {
	ID                uuid.UUID               `json:"id"`
	Symbol            string                  `json:"symbol"`
	Name              string                  `json:"name"`
	Currency          string                  `json:"currency"`
	AssetClass        AssetClass              `json:"assetClass"`
	LivePrice         scalar.Decimal          `json:"livePrice"`
	Isin              *string                 `json:"isin,omitempty"`
	Wkn               *string                 `json:"wkn,omitempty"`
	Issuer            *string                 `json:"issuer,omitempty"`
	ProviderProductID *string                 `json:"providerProductId,omitempty"`
	Holdings          []*EtfHolding           `json:"holdings"`
	Countries         []*EtfCountryAllocation `json:"countries"`
}

func (EtfAsset) IsAsset()                          {}
func (this EtfAsset) GetID() uuid.UUID             { return this.ID }
func (this EtfAsset) GetSymbol() string            { return this.Symbol }
func (this EtfAsset) GetName() string              { return this.Name }
func (this EtfAsset) GetCurrency() string          { return this.Currency }
func (this EtfAsset) GetAssetClass() AssetClass    { return this.AssetClass }
func (this EtfAsset) GetLivePrice() scalar.Decimal { return this.LivePrice }

type EtfCountryAllocation struct {
	CountryCode string         `json:"countryCode"`
	Percentage  scalar.Decimal `json:"percentage"`
}

type EtfHolding struct {
	Asset      Asset          `json:"asset"`
	Percentage scalar.Decimal `json:"percentage"`
}

type Query struct {
}

type StockAsset struct {
	ID          uuid.UUID      `json:"id"`
	Symbol      string         `json:"symbol"`
	Name        string         `json:"name"`
	Currency    string         `json:"currency"`
	AssetClass  AssetClass     `json:"assetClass"`
	LivePrice   scalar.Decimal `json:"livePrice"`
	Isin        *string        `json:"isin,omitempty"`
	Wkn         *string        `json:"wkn,omitempty"`
	Issuer      *string        `json:"issuer,omitempty"`
	CountryCode string         `json:"countryCode"`
}

func (StockAsset) IsAsset()                          {}
func (this StockAsset) GetID() uuid.UUID             { return this.ID }
func (this StockAsset) GetSymbol() string            { return this.Symbol }
func (this StockAsset) GetName() string              { return this.Name }
func (this StockAsset) GetCurrency() string          { return this.Currency }
func (this StockAsset) GetAssetClass() AssetClass    { return this.AssetClass }
func (this StockAsset) GetLivePrice() scalar.Decimal { return this.LivePrice }

type AssetClass string

const (
	AssetClassStock AssetClass = "STOCK"
	AssetClassEtf   AssetClass = "ETF"
)

var AllAssetClass = []AssetClass{
	AssetClassStock,
	AssetClassEtf,
}

func (e AssetClass) IsValid() bool {
	switch e {
	case AssetClassStock, AssetClassEtf:
		return true
	}
	return false
}

func (e AssetClass) String() string {
	return string(e)
}

func (e *AssetClass) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AssetClass(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AssetClass", str)
	}
	return nil
}

func (e AssetClass) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AssetClass) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AssetClass) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
