package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"
	"fmt"

	"github.com/julianahrens/balanceraybackend/internal/graph/model"
)

// Assets is the resolver for the assets field.
func (r *queryResolver) Assets(ctx context.Context) ([]model.Asset, error) {
	panic(fmt.Errorf("not implemented: Assets - assets"))
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
