# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import market_data_pb2 as market__data__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in market_data_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MarketDataServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetHistoricalOHLC = channel.unary_unary(
                '/marketdata.MarketDataService/GetHistoricalOHLC',
                request_serializer=market__data__pb2.HistoryRequest.SerializeToString,
                response_deserializer=market__data__pb2.HistoryResponse.FromString,
                _registered_method=True)
        self.GetLiveQuote = channel.unary_unary(
                '/marketdata.MarketDataService/GetLiveQuote',
                request_serializer=market__data__pb2.QuoteRequest.SerializeToString,
                response_deserializer=market__data__pb2.QuoteResponse.FromString,
                _registered_method=True)
        self.GetAssetMetadata = channel.unary_unary(
                '/marketdata.MarketDataService/GetAssetMetadata',
                request_serializer=market__data__pb2.AssetMetadataRequest.SerializeToString,
                response_deserializer=market__data__pb2.AssetMetadataResponse.FromString,
                _registered_method=True)
        self.GetDividends = channel.unary_unary(
                '/marketdata.MarketDataService/GetDividends',
                request_serializer=market__data__pb2.DividendsRequest.SerializeToString,
                response_deserializer=market__data__pb2.DividendsResponse.FromString,
                _registered_method=True)


class MarketDataServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetHistoricalOHLC(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLiveQuote(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAssetMetadata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDividends(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MarketDataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetHistoricalOHLC': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHistoricalOHLC,
                    request_deserializer=market__data__pb2.HistoryRequest.FromString,
                    response_serializer=market__data__pb2.HistoryResponse.SerializeToString,
            ),
            'GetLiveQuote': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLiveQuote,
                    request_deserializer=market__data__pb2.QuoteRequest.FromString,
                    response_serializer=market__data__pb2.QuoteResponse.SerializeToString,
            ),
            'GetAssetMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAssetMetadata,
                    request_deserializer=market__data__pb2.AssetMetadataRequest.FromString,
                    response_serializer=market__data__pb2.AssetMetadataResponse.SerializeToString,
            ),
            'GetDividends': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDividends,
                    request_deserializer=market__data__pb2.DividendsRequest.FromString,
                    response_serializer=market__data__pb2.DividendsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'marketdata.MarketDataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('marketdata.MarketDataService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MarketDataService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetHistoricalOHLC(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketdata.MarketDataService/GetHistoricalOHLC',
            market__data__pb2.HistoryRequest.SerializeToString,
            market__data__pb2.HistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLiveQuote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketdata.MarketDataService/GetLiveQuote',
            market__data__pb2.QuoteRequest.SerializeToString,
            market__data__pb2.QuoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAssetMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketdata.MarketDataService/GetAssetMetadata',
            market__data__pb2.AssetMetadataRequest.SerializeToString,
            market__data__pb2.AssetMetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDividends(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketdata.MarketDataService/GetDividends',
            market__data__pb2.DividendsRequest.SerializeToString,
            market__data__pb2.DividendsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
