// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jilio/gqlgen-scalars/scalar"
)

type AssetClass string

const (
	AssetClassSTOCK AssetClass = "STOCK"
	AssetClassETF   AssetClass = "ETF"
)

func (e *AssetClass) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AssetClass(s)
	case string:
		*e = AssetClass(s)
	default:
		return fmt.Errorf("unsupported scan type for AssetClass: %T", src)
	}
	return nil
}

type NullAssetClass struct {
	AssetClass AssetClass `json:"asset_class"`
	Valid      bool       `json:"valid"` // Valid is true if AssetClass is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAssetClass) Scan(value interface{}) error {
	if value == nil {
		ns.AssetClass, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AssetClass.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAssetClass) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AssetClass), nil
}

type Asset struct {
	ID         uuid.UUID      `json:"id"`
	Symbol     string         `json:"symbol"`
	Name       string         `json:"name"`
	Currency   string         `json:"currency"`
	AssetClass AssetClass     `json:"asset_class"`
	LivePrice  scalar.Decimal `json:"live_price"`
	UpdatedAt  time.Time      `json:"updated_at"`
}

type AssetsEtf struct {
	AssetID           uuid.UUID      `json:"asset_id"`
	Isin              sql.NullString `json:"isin"`
	Wkn               sql.NullString `json:"wkn"`
	Issuer            sql.NullString `json:"issuer"`
	ProviderProductID sql.NullString `json:"provider_product_id"`
}

type AssetsStock struct {
	AssetID     uuid.UUID      `json:"asset_id"`
	Isin        sql.NullString `json:"isin"`
	Wkn         sql.NullString `json:"wkn"`
	Issuer      sql.NullString `json:"issuer"`
	CountryCode string         `json:"country_code"`
}

type EtfAssetHolding struct {
	EtfAssetID     uuid.UUID      `json:"etf_asset_id"`
	HoldingAssetID uuid.UUID      `json:"holding_asset_id"`
	Percentage     scalar.Decimal `json:"percentage"`
}

type EtfCountryAllocation struct {
	EtfAssetID  uuid.UUID      `json:"etf_asset_id"`
	CountryCode string         `json:"country_code"`
	Percentage  scalar.Decimal `json:"percentage"`
}

type HistoricalPrice struct {
	AssetID    uuid.UUID `json:"asset_id"`
	PriceDate  time.Time `json:"price_date"`
	OpenPrice  string    `json:"open_price"`
	HighPrice  string    `json:"high_price"`
	LowPrice   string    `json:"low_price"`
	ClosePrice string    `json:"close_price"`
}
