// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateBaseAsset(ctx context.Context, arg CreateBaseAssetParams) (Asset, error)
	CreateEtfExtension(ctx context.Context, arg CreateEtfExtensionParams) error
	CreateStockExtension(ctx context.Context, arg CreateStockExtensionParams) error
	GetEtfExtensionByAssetID(ctx context.Context, assetID uuid.UUID) (AssetsEtf, error)
	GetHistoricalPrices(ctx context.Context, arg GetHistoricalPricesParams) ([]HistoricalPrice, error)
	GetStockExtensionByAssetID(ctx context.Context, assetID uuid.UUID) (AssetsStock, error)
	// Fetches the core fields of all assets. The extensions (Stock/ETF details)
	// should be loaded lazily or via batching to keep this initial query fast.
	ListAllAssets(ctx context.Context) ([]Asset, error)
}

var _ Querier = (*Queries)(nil)
