// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/jilio/gqlgen-scalars/scalar"
)

const createBaseAsset = `-- name: CreateBaseAsset :one
INSERT INTO assets (
    symbol, name, currency, asset_class, live_price
) VALUES (
             $1, $2, $3, $4, $5
         )
    RETURNING id, symbol, name, currency, asset_class, live_price, updated_at
`

type CreateBaseAssetParams struct {
	Symbol     string         `json:"symbol"`
	Name       string         `json:"name"`
	Currency   string         `json:"currency"`
	AssetClass AssetClass     `json:"asset_class"`
	LivePrice  scalar.Decimal `json:"live_price"`
}

func (q *Queries) CreateBaseAsset(ctx context.Context, arg CreateBaseAssetParams) (Asset, error) {
	row := q.db.QueryRowContext(ctx, createBaseAsset,
		arg.Symbol,
		arg.Name,
		arg.Currency,
		arg.AssetClass,
		arg.LivePrice,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.Name,
		&i.Currency,
		&i.AssetClass,
		&i.LivePrice,
		&i.UpdatedAt,
	)
	return i, err
}

const createEtfExtension = `-- name: CreateEtfExtension :exec
INSERT INTO assets_etf (
    asset_id, isin, wkn, issuer, provider_product_id
) VALUES (
             $1, $2, $3, $4, $5
         )
`

type CreateEtfExtensionParams struct {
	AssetID           uuid.UUID      `json:"asset_id"`
	Isin              sql.NullString `json:"isin"`
	Wkn               sql.NullString `json:"wkn"`
	Issuer            sql.NullString `json:"issuer"`
	ProviderProductID sql.NullString `json:"provider_product_id"`
}

func (q *Queries) CreateEtfExtension(ctx context.Context, arg CreateEtfExtensionParams) error {
	_, err := q.db.ExecContext(ctx, createEtfExtension,
		arg.AssetID,
		arg.Isin,
		arg.Wkn,
		arg.Issuer,
		arg.ProviderProductID,
	)
	return err
}

const createStockExtension = `-- name: CreateStockExtension :exec
INSERT INTO assets_stock (
    asset_id, isin, wkn, issuer, country_code
) VALUES (
             $1, $2, $3, $4, $5
         )
`

type CreateStockExtensionParams struct {
	AssetID     uuid.UUID      `json:"asset_id"`
	Isin        sql.NullString `json:"isin"`
	Wkn         sql.NullString `json:"wkn"`
	Issuer      sql.NullString `json:"issuer"`
	CountryCode string         `json:"country_code"`
}

func (q *Queries) CreateStockExtension(ctx context.Context, arg CreateStockExtensionParams) error {
	_, err := q.db.ExecContext(ctx, createStockExtension,
		arg.AssetID,
		arg.Isin,
		arg.Wkn,
		arg.Issuer,
		arg.CountryCode,
	)
	return err
}

const getEtfExtensionByAssetID = `-- name: GetEtfExtensionByAssetID :one
SELECT asset_id, isin, wkn, issuer, provider_product_id
FROM assets_etf
WHERE asset_id = $1
`

func (q *Queries) GetEtfExtensionByAssetID(ctx context.Context, assetID uuid.UUID) (AssetsEtf, error) {
	row := q.db.QueryRowContext(ctx, getEtfExtensionByAssetID, assetID)
	var i AssetsEtf
	err := row.Scan(
		&i.AssetID,
		&i.Isin,
		&i.Wkn,
		&i.Issuer,
		&i.ProviderProductID,
	)
	return i, err
}

const getHistoricalPrices = `-- name: GetHistoricalPrices :many
SELECT asset_id, price_date, open_price, high_price, low_price, close_price
FROM historical_prices
WHERE asset_id = $1 AND price_date >= $2
ORDER BY price_date DESC
`

type GetHistoricalPricesParams struct {
	AssetID   uuid.UUID `json:"asset_id"`
	PriceDate time.Time `json:"price_date"`
}

func (q *Queries) GetHistoricalPrices(ctx context.Context, arg GetHistoricalPricesParams) ([]HistoricalPrice, error) {
	rows, err := q.db.QueryContext(ctx, getHistoricalPrices, arg.AssetID, arg.PriceDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HistoricalPrice
	for rows.Next() {
		var i HistoricalPrice
		if err := rows.Scan(
			&i.AssetID,
			&i.PriceDate,
			&i.OpenPrice,
			&i.HighPrice,
			&i.LowPrice,
			&i.ClosePrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStockExtensionByAssetID = `-- name: GetStockExtensionByAssetID :one
SELECT asset_id, isin, wkn, issuer, country_code
FROM assets_stock
WHERE asset_id = $1
`

func (q *Queries) GetStockExtensionByAssetID(ctx context.Context, assetID uuid.UUID) (AssetsStock, error) {
	row := q.db.QueryRowContext(ctx, getStockExtensionByAssetID, assetID)
	var i AssetsStock
	err := row.Scan(
		&i.AssetID,
		&i.Isin,
		&i.Wkn,
		&i.Issuer,
		&i.CountryCode,
	)
	return i, err
}

const listAllAssets = `-- name: ListAllAssets :many
SELECT id, symbol, name, currency, asset_class, live_price, updated_at
FROM assets
ORDER BY name ASC
`

// Fetches the core fields of all assets. The extensions (Stock/ETF details)
// should be loaded lazily or via batching to keep this initial query fast.
func (q *Queries) ListAllAssets(ctx context.Context) ([]Asset, error) {
	rows, err := q.db.QueryContext(ctx, listAllAssets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Asset
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.Symbol,
			&i.Name,
			&i.Currency,
			&i.AssetClass,
			&i.LivePrice,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllAssetsWithExtensions = `-- name: ListAllAssetsWithExtensions :many
SELECT
    a.id, a.symbol, a.name, a.currency, a.asset_class, a.live_price, a.updated_at,
    s.isin AS stock_isin, s.wkn AS stock_wkn, s.issuer AS stock_issuer, s.country_code,
    e.isin AS etf_isin, e.wkn AS etf_wkn, e.issuer AS etf_issuer, e.provider_product_id
FROM assets a
         LEFT JOIN assets_stock s ON a.id = s.asset_id AND a.asset_class = 'STOCK'
         LEFT JOIN assets_etf e ON a.id = e.asset_id AND a.asset_class = 'ETF'
ORDER BY a.name ASC
`

type ListAllAssetsWithExtensionsRow struct {
	ID                uuid.UUID      `json:"id"`
	Symbol            string         `json:"symbol"`
	Name              string         `json:"name"`
	Currency          string         `json:"currency"`
	AssetClass        AssetClass     `json:"asset_class"`
	LivePrice         scalar.Decimal `json:"live_price"`
	UpdatedAt         time.Time      `json:"updated_at"`
	StockIsin         sql.NullString `json:"stock_isin"`
	StockWkn          sql.NullString `json:"stock_wkn"`
	StockIssuer       sql.NullString `json:"stock_issuer"`
	CountryCode       sql.NullString `json:"country_code"`
	EtfIsin           sql.NullString `json:"etf_isin"`
	EtfWkn            sql.NullString `json:"etf_wkn"`
	EtfIssuer         sql.NullString `json:"etf_issuer"`
	ProviderProductID sql.NullString `json:"provider_product_id"`
}

func (q *Queries) ListAllAssetsWithExtensions(ctx context.Context) ([]ListAllAssetsWithExtensionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllAssetsWithExtensions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllAssetsWithExtensionsRow
	for rows.Next() {
		var i ListAllAssetsWithExtensionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Symbol,
			&i.Name,
			&i.Currency,
			&i.AssetClass,
			&i.LivePrice,
			&i.UpdatedAt,
			&i.StockIsin,
			&i.StockWkn,
			&i.StockIssuer,
			&i.CountryCode,
			&i.EtfIsin,
			&i.EtfWkn,
			&i.EtfIssuer,
			&i.ProviderProductID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAssetPrice = `-- name: UpdateAssetPrice :exec
UPDATE assets
SET live_price = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateAssetPriceParams struct {
	ID        uuid.UUID      `json:"id"`
	LivePrice scalar.Decimal `json:"live_price"`
}

func (q *Queries) UpdateAssetPrice(ctx context.Context, arg UpdateAssetPriceParams) error {
	_, err := q.db.ExecContext(ctx, updateAssetPrice, arg.ID, arg.LivePrice)
	return err
}
